---
- name: install nagios reqs
    apt:
      name: 
        - autoconf
        - gcc
        - libc6
        - make
        - wget
        - unzip
        - libssl-dev
        - apache2
        - php
        - libapache2-mod-php*
        - libgd-dev
        - build-essential
      state: latest
      force: true
      update_cache: true
    become: true
