---
- name: Install Nagios Dependencies
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - libssl-dev
      - apache2
      - php
      - libapache2-mod-php*
      - libgd-dev
      - build-essential
    state: latest
    update_cache: yes
    
- name: Start Nagios service
  service:
    name: nagios
    state: restarted
