---
- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: prometheus args
  template:
    src: "files/prometheus.j2"
    dest: "/etc/default/prometheus"
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus
- name: prometheus configuration file
  template:
    src: "files/prometheus.yaml.j2"
    dest: "{{ prometheus_dir_configuration }}/prometheus.yaml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: restart_prometheus
- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
